### ISSUE TITLE
Console App

### ISSUE THREAD

**Issue by alexxxius** [aspnet/Docs.it-it#29]
Microsoft.AspNetCore.Hosting.WindowsServices  is a package for asp.net core, but if I would a simply console app? Is possible deploy as service a console app?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: b0bd8cb8-7e28-8c4d-a550-3aea8f3ab4dd
* Version Independent ID: 4b60d24e-ef05-15e5-10b4-483094081bf3
* Content: [Ospitare ASP.NET Core in un servizio Windows](https://docs.microsoft.com/it-it/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2)
* Content Source: [aspnetcore/host-and-deploy/windows-service.md](https://github.com/aspnet/docs.it-it/blob/live/aspnetcore/host-and-deploy/windows-service.md)
* Product: **aspnet-core**
* GitHub Login: @guardrex
* Microsoft Alias: **tdykstra**

**Comment by guardrex** [comment]
Hello @alexxxius ... All .NET Core apps are console apps. Are you asking if you can make an app work without the package? Yes, that should be possible **_BUT_** only if you take the code that's included in the package and use it in the app to provide the app with the hosting infrastructure required to run as a Windows Service.

Note that the package name will change for 3.0 to either `Microsoft.Extensions.Hosting.WindowsService` or `Microsoft.Extensions.Hosting.WindowsServices`. For more info, see https://github.com/aspnet/Extensions/pull/1083.

**Comment by CeciAc** [comment]
Hello, @alexxxius 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
